kind = "web"
previewPath = "/"
title = "Hălchiu Digital"
version = "1.0.0"
id = "artifacts/halchiu-digital"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/", "/api", "/vite-hmr" ]
localPort = 18355

[services.development]
run = "pnpm --filter @workspace/halchiu-digital run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/halchiu-digital", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/halchiu-digital", "run", "start" ]

[services.env]
PORT = "18355"
